import {makeCuratedDemos, type CuratedDemoDefinition} from '../curated/CuratedScene';

export const rveAdditions: CuratedDemoDefinition[] = [
  {id: 'Rve-AreaChart', name: 'Area Chart', slug: 'area-chart',
    variant: 'area-chart', title: '趋势面积图', kicker: 'trend', accent: '#38BDF8',
    secondary: 'growth over time', durationInFrames: 210},
  {id: 'Rve-CircularProgress', name: 'Circular Progress', slug: 'circular-progress',
    variant: 'circular-progress', title: '完成度环形进度', kicker: 'progress', accent: '#22C55E',
    secondary: 'delivery ratio', durationInFrames: 180},
  {id: 'Rve-AnimatedList', name: 'Animated List', slug: 'animated-list',
    variant: 'animated-list', title: '步骤依次出现', kicker: 'list', accent: '#FACC15',
    secondary: 'ordered points', durationInFrames: 180},
  {id: 'Rve-NotificationPop', name: 'Notification Pop', slug: 'notification-pop',
    variant: 'notification-pop', title: '通知卡片弹出', kicker: 'notification', accent: '#FB7185',
    secondary: 'status update', durationInFrames: 180},
  {id: 'Rve-SoundWave', name: 'Sound Wave', slug: 'sound-wave',
    variant: 'sound-wave', title: '音频波形强调', kicker: 'audio', accent: '#2DD4BF',
    secondary: 'voice segment', durationInFrames: 210},
  {id: 'Rve-TextHighlight', name: 'Text Highlight', slug: 'text-highlight',
    variant: 'text-highlight', title: 'Highlight This', kicker: 'emphasis', accent: '#F97316',
    secondary: 'keyword emphasis', durationInFrames: 150},
  {id: 'Rve-GalleryGrid', name: 'Gallery Grid', slug: 'gallery-grid',
    variant: 'gallery-grid', title: '多素材网格展示', kicker: 'gallery', accent: '#60A5FA',
    secondary: 'image set', durationInFrames: 210},
  {id: 'Rve-ImageCarousel', name: 'Image Carousel', slug: 'image-carousel',
    variant: 'image-carousel', title: '图片轮播切换', kicker: 'carousel', accent: '#A3E635',
    secondary: 'sequence', durationInFrames: 220},
  {id: 'Rve-ImageZoomReveal', name: 'Image Zoom Reveal', slug: 'image-zoom-reveal',
    variant: 'image-zoom-reveal', title: '图片推近揭示细节', kicker: 'zoom reveal', accent: '#38BDF8',
    secondary: 'focus point', durationInFrames: 210},
  {id: 'Rve-MasonryGallery', name: 'Masonry Gallery', slug: 'masonry-gallery',
    variant: 'masonry-gallery', title: '瀑布流素材墙', kicker: 'masonry', accent: '#F43F5E',
    secondary: 'visual evidence', durationInFrames: 210},
  {id: 'Rve-PhotoStack', name: 'Photo Stack', slug: 'photo-stack',
    variant: 'photo-stack', title: '照片堆叠展开', kicker: 'photo stack', accent: '#FACC15',
    secondary: 'story moments', durationInFrames: 180},
  {id: 'Rve-PictureInPicture', name: 'Picture In Picture', slug: 'picture-in-picture',
    variant: 'picture-in-picture', title: '主画面加讲解小窗', kicker: 'pip', accent: '#2DD4BF',
    secondary: 'speaker inset', durationInFrames: 210},
  {id: 'Rve-PolaroidFrame', name: 'Polaroid Frame', slug: 'polaroid-frame',
    variant: 'polaroid-frame', title: '拍立得素材卡', kicker: 'polaroid', accent: '#F97316',
    secondary: 'memory card', durationInFrames: 180},
  {id: 'Rve-ClockWipe', name: 'Clock Wipe', slug: 'clock-wipe',
    variant: 'clock-wipe', title: '时钟形转场', kicker: 'transition', accent: '#38BDF8',
    secondary: 'section change', durationInFrames: 150},
  {id: 'Rve-IrisTransition', name: 'Iris Transition', slug: 'iris-transition',
    variant: 'iris-transition', title: '圆形开合转场', kicker: 'transition', accent: '#A3E635',
    secondary: 'focus reveal', durationInFrames: 150},
];

export const rveCuratedDemos = makeCuratedDemos(
  rveAdditions,
  'landscape',
  {width: 1280, height: 720},
);
