"""Export the canonical Pydantic contracts; run with .venv-videoagents Python."""

import argparse
import inspect
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from videoagents.contracts import models  # noqa: E402


def ts_type(schema: dict[str, Any], partial_objects: bool = False) -> str:
    if "$ref" in schema:
        reference = schema["$ref"].rsplit("/", 1)[-1]
        return f"Partial<{reference}>" if partial_objects else reference
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(dict.fromkeys(ts_type(value, partial_objects) for value in schema["anyOf"]))
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object":
        additional = schema.get("additionalProperties")
        if not schema.get("properties"):
            keys = schema.get("propertyNames", {}).get("enum")
            if keys and isinstance(additional, dict):
                names = " | ".join(json.dumps(key) for key in keys)
                return f"Partial<Record<{names}, {ts_type(additional, partial_objects)}>>"
            return f"Record<string, {ts_type(additional) if isinstance(additional, dict) else 'unknown'}>"
        required = set(schema.get("required", []))
        fields = [f"{json.dumps(key)}{'' if key in required else '?'}: {ts_type(value)}" for key, value in schema["properties"].items()]
        return "{ " + "; ".join(fields) + " }"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def outputs() -> dict[Path, str]:
    schemas: dict[str, Any] = {}
    canonical = [value for _, value in inspect.getmembers(models, inspect.isclass)
                 if value.__module__ == models.__name__ and issubclass(value, models.Contract) and value is not models.Contract]
    for model in canonical:
        schema = model.model_json_schema()
        schemas.update(schema.pop("$defs", {}))
        schemas[model.__name__] = schema
    lines = ["// Generated by scripts/export-contracts.py. Edit Python contracts, then regenerate.", ""]
    requests = {"DraftRequest", "RunRequest", "ResumeRequest", "SettingsPatch"}
    for name, schema in sorted(schemas.items()):
        required = set(schema.get("required", []))
        lines.append(f"export interface {name} {{")
        for field, spec in schema.get("properties", {}).items():
            # Responses are full model_dump objects; request defaults remain optional.
            optional = name in requests and field not in required
            partial_objects = name == "SettingsPatch" and field == "role_models"
            lines.append(f"  {field}{'?' if optional else ''}: {ts_type(spec, partial_objects)};")
        lines.extend(["}", ""])
    destination = ROOT / "contracts" / "generated"
    result = {
        destination / "models.ts": "\n".join(lines),
        destination / "schemas.json": json.dumps({"$schema": "https://json-schema.org/draft/2020-12/schema", "$defs": schemas}, ensure_ascii=False, indent=2) + "\n",
    }
    if (ROOT / "server" / "main.py").exists():
        import tempfile

        from server.main import create_app
        # Exporting does not modify the real runtime database or settings.
        with tempfile.TemporaryDirectory(prefix="videoagents-contract-") as temporary:
            app = create_app(runtime_dir=Path(temporary))
            result[destination / "openapi.json"] = json.dumps(app.openapi(), ensure_ascii=False, indent=2) + "\n"
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when committed exports differ from Python contracts")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(path.relative_to(ROOT))
    if stale:
        print("Contract exports need regeneration: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
